<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('ciudads', function (Blueprint $table) {
            $table->id();
            $table->string('nombre_ciudad');
            $table->foreignId('departamento_id')->constrained();
        });

        DB::table('ciudads')->insert([
            // Amazonas por orden alfabético
            ['nombre_ciudad' => 'Leticia', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Puerto Nariño', 'departamento_id' => 1],
            ['nombre_ciudad' => 'El Encanto', 'departamento_id' => 1],
            ['nombre_ciudad' => 'La Chorrera', 'departamento_id' => 1],
            ['nombre_ciudad' => 'La Pedrera', 'departamento_id' => 1],
            ['nombre_ciudad' => 'La Victoria', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Miriti - Paraná', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Puerto Alegría', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Puerto Arica', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Puerto Santander', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Tarapacá', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Yavaraté', 'departamento_id' => 1],

            // Antioquia
            ['nombre_ciudad' => 'Abejorral', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Abriaquí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Alejandría', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Amagá', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Amalfi', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Andes', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Angelópolis', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Angostura', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Anorí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Anzá', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Apartadó', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Arboletes', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Argelia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Armenia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Barbosa', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Bello', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Belmira', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Betania', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Betulia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Briceño', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Buriticá', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Cáceres', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Caicedo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Caldas', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Campamento', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Cañasgordas', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Caracolí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Caramanta', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Carepa', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Carolina', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Caucasia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Chigorodó', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Cisneros', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Ciudad Bolívar', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Cocorná', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Concepción', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Concordia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Copacabana', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Dabeiba', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Donmatías', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Ebéjico', 'departamento_id' => 2],
            ['nombre_ciudad' => 'El Bagre', 'departamento_id' => 2],
            ['nombre_ciudad' => 'El Carmen de Viboral', 'departamento_id' => 2],
            ['nombre_ciudad' => 'El Peñol', 'departamento_id' => 2],
            ['nombre_ciudad' => 'El Retiro', 'departamento_id' => 2],
            ['nombre_ciudad' => 'El Santuario', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Entrerríos', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Envigado', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Fredonia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Frontino', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Giraldo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Girardota', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Gómez Plata', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Granada', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Guadalupe', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Guarne', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Guatapé', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Heliconia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Hispania', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Itagüí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Ituango', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Jardín', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Jericó', 'departamento_id' => 2],
            ['nombre_ciudad' => 'La Ceja', 'departamento_id' => 2],
            ['nombre_ciudad' => 'La Estrella', 'departamento_id' => 2],
            ['nombre_ciudad' => 'La Pintada', 'departamento_id' => 2],
            ['nombre_ciudad' => 'La Unión', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Liborina', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Maceo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Marinilla', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Medellín', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Montebello', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Murindó', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Mutatá', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Nariño', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Nechí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Necoclí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Olaya', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Peque', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Pueblorrico', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Puerto Berrío', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Puerto Nare', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Puerto Triunfo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Remedios', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Rionegro', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Sabanalarga', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Sabaneta', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Salgar', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Andrés de Cuerquía', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Carlos', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Francisco', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Jerónimo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San José de la Montaña', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Juan de Urabá', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Luis', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Pedro de los Milagros', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Pedro de Urabá', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Rafael', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Roque', 'departamento_id' => 2],
            ['nombre_ciudad' => 'San Vicente', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Santa Bárbara', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Santa Fe de Antioquia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Santa Rosa de Osos', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Santo Domingo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Segovia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Sonsón', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Sopetrán', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Támesis', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Tarazá', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Tarso', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Titiribí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Toledo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Turbo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Uramita', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Urrao', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Valdivia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Valparaíso', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Vegachí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Venecia', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Vigía del Fuerte', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Yalí', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Yarumal', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Yolombó', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Yondó', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Zaragoza', 'departamento_id' => 2],

            // Arauca
            ['nombre_ciudad' => 'Arauca', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Arauquita', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Cravo Norte', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Fortul', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Puerto Rondón', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Saravena', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Tame', 'departamento_id' => 3],

            // Atlantico
            ['nombre_ciudad' => 'Baranoa', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Barranquilla', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Campo de la Cruz', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Candelaria', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Galapa', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Juan de Acosta', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Luruaco', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Malambo', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Manatí', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Palmar de Varela', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Piojó', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Polonuevo', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Ponedera', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Puerto Colombia', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Repelón', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Sabanagrande', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Sabanalarga', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Santa Lucía', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Santo Tomás', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Soledad', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Suan', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Tubará', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Usiacurí', 'departamento_id' => 4],

            // Bolvar
            ['nombre_ciudad' => 'Achí', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Altos del Rosario', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Arenal', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Arjona', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Arroyohondo', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Barranco de Loba', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Cantagallo', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Cartagena de Indias', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Cicuco', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Clemencia', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Córdoba', 'departamento_id' => 5],
            ['nombre_ciudad' => 'El Carmen de Bolívar', 'departamento_id' => 5],
            ['nombre_ciudad' => 'El Guamo', 'departamento_id' => 5],
            ['nombre_ciudad' => 'El Peñón', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Hatillo de Loba', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Magangué', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Mahates', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Margarita', 'departamento_id' => 5],
            ['nombre_ciudad' => 'María la Baja', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Montecristo', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Morales', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Norosí', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Pinillos', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Regidor', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Río Viejo', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Cristóbal', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Estanislao', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Fernando', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Jacinto', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Jacinto del Cauca', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Juan Nepomuceno', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Martín de Loba', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Pablo', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Santa Catalina', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Santa Rosa', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Santa Rosa del Sur', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Simití', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Soplaviento', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Talaigua Nuevo', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Tiquisio', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Turbaco', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Turbaná', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Villanueva', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Zambrano', 'departamento_id' => 5],

            // Boyaca
            ['nombre_ciudad' => 'Almeida', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Aquitania', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Arcabuco', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Belén', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Berbeo', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Betéitiva', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Boavita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Boyacá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Briceño', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Buena Vista', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Busbanzá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Caldas', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Campohermoso', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Cerinza', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Chinavita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Chiquinquirá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Chiscas', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Chita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Chitaraque', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Chivatá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Chivor', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Ciénega', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Cómbita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Coper', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Corrales', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Covarachía', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Cubará', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Cucaita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Cuítiva', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Duitama', 'departamento_id' => 6],
            ['nombre_ciudad' => 'El Cocuy', 'departamento_id' => 6],
            ['nombre_ciudad' => 'El Espino', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Firavitoba', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Floresta', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Gachantivá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Gámeza', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Garagoa', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Guacamayas', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Guateque', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Guayatá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Güicán', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Iza', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Jenesano', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Jericó', 'departamento_id' => 6],
            ['nombre_ciudad' => 'La Capilla', 'departamento_id' => 6],
            ['nombre_ciudad' => 'La Uvita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'La Victoria', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Labranzagrande', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Macanal', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Maripí', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Mongua', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Monguí', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Moniquirá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Motavita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Muzo', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Nobsa', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Nuevo Colón', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Oicatá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Otanche', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Pachavita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Paipa', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Pajarito', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Panqueba', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Pauna', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Paya', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Paz de Río', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Pesca', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Pisba', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Puerto Boyacá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Quípama', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Ramiriquí', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Ráquira', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Rondón', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Saboyá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Sáchica', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Samacá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San Eduardo', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San José de Pare', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San Luis de Gaceno', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San Mateo', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San Miguel de Sema', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San Pablo de Borbur', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Santa María', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Santa Rosa de Viterbo', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Santa Sofía', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Santana', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Sativanorte', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Sativasur', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Siachoque', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Soatá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Socha', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Socotá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Sogamoso', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Somondoco', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Sora', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Soracá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Sotaquirá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Susacón', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Sutamarchán', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Sutatenza', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tasco', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tenza', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tibaná', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tibasosa', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tinjacá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tipacoque', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Toca', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Togüí', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tópaga', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tota', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tunja', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tununguá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Turmequé', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tuta', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tutazá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Umbita', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Ventaquemada', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Villa de Leyva', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Viracachá', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Zetaquira', 'departamento_id' => 6],

            // Caldas
            ['nombre_ciudad' => 'Aguadas', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Anserma', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Aranzazu', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Belalcázar', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Chinchiná', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Filadelfia', 'departamento_id' => 7],
            ['nombre_ciudad' => 'La Dorada', 'departamento_id' => 7],
            ['nombre_ciudad' => 'La Merced', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Manizales', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Manzanares', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Marmato', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Marquetalia', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Marulanda', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Neira', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Norcasia', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Pácora', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Palestina', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Pensilvania', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Riosucio', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Risaralda', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Salamina', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Samaná', 'departamento_id' => 7],
            ['nombre_ciudad' => 'San José', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Supía', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Victoria', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Villamaría', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Viterbo', 'departamento_id' => 7],

            // Caqueta
            ['nombre_ciudad' => 'Albania', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Belén de los Andaquíes', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Cartagena del Chairá', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Curillo', 'departamento_id' => 8],
            ['nombre_ciudad' => 'El Doncello', 'departamento_id' => 8],
            ['nombre_ciudad' => 'El Paujil', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Florencia', 'departamento_id' => 8],
            ['nombre_ciudad' => 'La Montañita', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Milán', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Morelia', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Puerto Rico', 'departamento_id' => 8],
            ['nombre_ciudad' => 'San José del Fragua', 'departamento_id' => 8],
            ['nombre_ciudad' => 'San Vicente del Caguán', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Solano', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Solita', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Valparaíso', 'departamento_id' => 8],

            //Casanare
            ['nombre_ciudad' => 'Aguazul', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Chámeza', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Hato Corozal', 'departamento_id' => 9],
            ['nombre_ciudad' => 'La Salina', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Maní', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Monterrey', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Nunchía', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Orocué', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Paz de Ariporo', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Pore', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Recetor', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Sabanalarga', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Sacama', 'departamento_id' => 9],
            ['nombre_ciudad' => 'San Luis de Palenque', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Támara', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Tauramena', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Trinidad', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Villanueva', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Yopal', 'departamento_id' => 9],

            //Cauca
            ['nombre_ciudad' => 'Almaguer', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Argelia', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Balboa', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Bolívar', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Buenos Aires', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Cajibío', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Caldono', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Caloto', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Corinto', 'departamento_id' => 10],
            ['nombre_ciudad' => 'El Tambo', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Florencia', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Guachené', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Guapí', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Inzá', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Jambaló', 'departamento_id' => 10],
            ['nombre_ciudad' => 'La Sierra', 'departamento_id' => 10],
            ['nombre_ciudad' => 'La Vega', 'departamento_id' => 10],
            ['nombre_ciudad' => 'López de Micay', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Mercaderes', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Miranda', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Morales', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Padilla', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Páez', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Patía', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Piamonte', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Piendamó', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Popayán', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Puerto Tejada', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Puracé', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Rosas', 'departamento_id' => 10],
            ['nombre_ciudad' => 'San Sebastián', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Santa Rosa', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Santander de Quilichao', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Silvia', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Sotará', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Suárez', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Timbío', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Timbiquí', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Toribío', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Totoró', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Villa Rica', 'departamento_id' => 10],

            // Cesar
            ['nombre_ciudad' => 'Aguachica', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Agustín Codazzi', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Astrea', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Becerril', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Bosconia', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Chimichagua', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Chiriguaná', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Curumaní', 'departamento_id' => 11],
            ['nombre_ciudad' => 'El Copey', 'departamento_id' => 11],
            ['nombre_ciudad' => 'El Paso', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Gamarra', 'departamento_id' => 11],
            ['nombre_ciudad' => 'González', 'departamento_id' => 11],
            ['nombre_ciudad' => 'La Gloria', 'departamento_id' => 11],
            ['nombre_ciudad' => 'La Jagua de Ibirico', 'departamento_id' => 11],
            ['nombre_ciudad' => 'La Paz', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Manaure Balcón del Cesar', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Pailitas', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Pelaya', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Pueblo Bello', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Río de Oro', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San Alberto', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San Diego', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San Martín', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Tamalameque', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Valledupar', 'departamento_id' => 11],

            // Choco
            ['nombre_ciudad' => 'Acandí', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Alto Baudó', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Bagadó', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Bahía Solano', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Bajo Baudó', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Bojayá', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Cantón de San Pablo', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Cértegui', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Condoto', 'departamento_id' => 12],
            ['nombre_ciudad' => 'El Atrato', 'departamento_id' => 12],
            ['nombre_ciudad' => 'El Carmen de Atrato', 'departamento_id' => 12],
            ['nombre_ciudad' => 'El Carmen del Darién', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Istmina', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Juradó', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Lloró', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Medio Atrato', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Medio Baudó', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Medio San Juan', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Nóvita', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Nuquí', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Quibdó', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Río Iró', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Río Quito', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Riosucio', 'departamento_id' => 12],
            ['nombre_ciudad' => 'San José del Palmar', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Sipí', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Tadó', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Unguía', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Unión Panamericana', 'departamento_id' => 12],

            // Cordoba
            ['nombre_ciudad' => 'Ayapel', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Buenavista', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Canalete', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Cereté', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Chimá', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Chinú', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Ciénaga de Oro', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Cotorra', 'departamento_id' => 13],
            ['nombre_ciudad' => 'La Apartada', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Lorica', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Los Córdobas', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Momil', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Montelíbano', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Montería', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Moñitos', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Planeta Rica', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Pueblo Nuevo', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Puerto Escondido', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Puerto Libertador', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Purísima', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Sahagún', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Andrés de Sotavento', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Antero', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Bernardo del Viento', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Carlos', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San José de Uré', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Pelayo', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Tierralta', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Tuchín', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Valencia', 'departamento_id' => 13],

            // Cundinamarca
            ['nombre_ciudad' => 'Agua de Dios', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Albán', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Anapoima', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Anolaima', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Apulo', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Arbeláez', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Beltrán', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Bituima', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Bojacá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Cabrera', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Cachipay', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Cajicá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Caparrapí', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Cáqueza', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Carmen de Carupa', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Chaguaní', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Chía', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Chipaque', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Choachí', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Chocontá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Cogua', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Cota', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Cucunubá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'El Colegio', 'departamento_id' => 14],
            ['nombre_ciudad' => 'El Peñón', 'departamento_id' => 14],
            ['nombre_ciudad' => 'El Rosal', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Facatativá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Fómeque', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Fosca', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Funza', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Fúquene', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Fusagasugá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Gachalá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Gachancipá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Gachetá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Gama', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Girardot', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Granada', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Guachetá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Guaduas', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Guasca', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Guataquí', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Guatavita', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Guayabal de Síquima', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Guayabetal', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Gutiérrez', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Jerusalén', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Junín', 'departamento_id' => 14],
            ['nombre_ciudad' => 'La Calera', 'departamento_id' => 14],
            ['nombre_ciudad' => 'La Mesa', 'departamento_id' => 14],
            ['nombre_ciudad' => 'La Palma', 'departamento_id' => 14],
            ['nombre_ciudad' => 'La Peña', 'departamento_id' => 14],
            ['nombre_ciudad' => 'La Vega', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Lenguazaque', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Machetá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Madrid', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Manta', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Medina', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Mosquera', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Nariño', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Nemocón', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Nilo', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Nimaima', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Nocaima', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Venecia', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Vergara', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Vianí', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Villagómez', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Villapinzón', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Villeta', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Viotá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Yacopí', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Zipacón', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Zipaquirá', 'departamento_id' => 14],

            // Guainia
            ['nombre_ciudad' => 'Inírida', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Barranco Minas', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Mapiripana', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Felipe', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Puerto Colombia', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Guadalupe', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cacahual', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Pana Pana', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Morichal', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Puerres', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Remanso', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Juan del Cesar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Santa Rosalía', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Tame', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Carurú', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Puerto Inírida', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 15],

            // Guaviare
            ['nombre_ciudad' => 'Albania', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Barranco Minas', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Calamar', 'departamento_id' => 16],
            ['nombre_ciudad' => 'El Retorno', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Miraflores', 'departamento_id' => 16],
            ['nombre_ciudad' => 'San José del Guaviare', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 16],

            // Huila
            ['nombre_ciudad' => 'Acevedo', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Agrado', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Aipe', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Algeciras', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Altamira', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Baraya', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Campoalegre', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Colombia', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Elías', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Garzón', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Gigante', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Guadalupe', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Hobo', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Íquira', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Isnos', 'departamento_id' => 17],
            ['nombre_ciudad' => 'La Argentina', 'departamento_id' => 17],
            ['nombre_ciudad' => 'La Plata', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Nátaga', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Neiva', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Oporapa', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Paicol', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Palermo', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Palestina', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Pital', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Pitalito', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Rivera', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Saladoblanco', 'departamento_id' => 17],
            ['nombre_ciudad' => 'San Agustín', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Santa María', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Suaza', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Tarqui', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Tello', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Teruel', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Tesalia', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Timaná', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Villavieja', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Yaguará', 'departamento_id' => 17],

            // La Guajira
            ['nombre_ciudad' => 'Albania', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Barrancas', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Dibulla', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Distracción', 'departamento_id' => 18],
            ['nombre_ciudad' => 'El Molino', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Fonseca', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Hatonuevo', 'departamento_id' => 18],
            ['nombre_ciudad' => 'La Jagua del Pilar', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Maicao', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Manaure', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Riohacha', 'departamento_id' => 18],
            ['nombre_ciudad' => 'San Juan del Cesar', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Uribia', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Urumita', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Villanueva', 'departamento_id' => 18],

            // Magdalena
            ['nombre_ciudad' => 'Algarrobo', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Aracataca', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Ariguaní', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Cerro de San Antonio', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Chibolo', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Ciénaga', 'departamento_id' => 19],
            ['nombre_ciudad' => 'El Banco', 'departamento_id' => 19],
            ['nombre_ciudad' => 'El Piñón', 'departamento_id' => 19],
            ['nombre_ciudad' => 'El Retén', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Fundación', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Guamal', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Nueva Granada', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Pedraza', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Pijiño del Carmen', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Pivijay', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Plato', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Puebloviejo', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Remolino', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Sabanas de San Ángel', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Salamina', 'departamento_id' => 19],
            ['nombre_ciudad' => 'San Sebastián de Buenavista', 'departamento_id' => 19],
            ['nombre_ciudad' => 'San Zenón', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Santa Ana', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Santa Bárbara de Pinto', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Santa Marta', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Sitionuevo', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Tenerife', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Zapayán', 'departamento_id' => 19],
            ['nombre_ciudad' => 'Zona Bananera', 'departamento_id' => 19],

            // Meta
            ['nombre_ciudad' => 'Acacías', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Barranca de Upía', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Cabuyaro', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Castilla la Nueva', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Cubarral', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Cumaral', 'departamento_id' => 20],
            ['nombre_ciudad' => 'El Calvario', 'departamento_id' => 20],
            ['nombre_ciudad' => 'El Castillo', 'departamento_id' => 20],
            ['nombre_ciudad' => 'El Dorado', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Fuente de Oro', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Granada', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Guamal', 'departamento_id' => 20],
            ['nombre_ciudad' => 'La Macarena', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Lejanías', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Mapiripán', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Mesetas', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Puerto Concordia', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Puerto Gaitán', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Puerto Lleras', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Puerto López', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Puerto Rico', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Restrepo', 'departamento_id' => 20],
            ['nombre_ciudad' => 'San Carlos de Guaroa', 'departamento_id' => 20],
            ['nombre_ciudad' => 'San Juan de Arama', 'departamento_id' => 20],
            ['nombre_ciudad' => 'San Juanito', 'departamento_id' => 20],
            ['nombre_ciudad' => 'San Martín', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Uribe', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Villavicencio', 'departamento_id' => 20],
            ['nombre_ciudad' => 'Vista Hermosa', 'departamento_id' => 20],

            // Nariño
            ['nombre_ciudad' => 'Albán', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Aldana', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Ancuyá', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Arboleda', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Barbacoas', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Belén', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Buesaco', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Chachagüí', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Colón', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Consacá', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Contadero', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Córdoba', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Cuaspud', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Cumbal', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Cumbitara', 'departamento_id' => 21],
            ['nombre_ciudad' => 'El Charco', 'departamento_id' => 21],
            ['nombre_ciudad' => 'El Peñol', 'departamento_id' => 21],
            ['nombre_ciudad' => 'El Rosario', 'departamento_id' => 21],
            ['nombre_ciudad' => 'El Tablón', 'departamento_id' => 21],
            ['nombre_ciudad' => 'El Tambo', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Francisco Pizarro', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Funes', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Guachucal', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Guaitarilla', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Gualmatán', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Iles', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Imués', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Ipiales', 'departamento_id' => 21],
            ['nombre_ciudad' => 'La Cruz', 'departamento_id' => 21],
            ['nombre_ciudad' => 'La Florida', 'departamento_id' => 21],
            ['nombre_ciudad' => 'La Llanada', 'departamento_id' => 21],
            ['nombre_ciudad' => 'La Tola', 'departamento_id' => 21],
            ['nombre_ciudad' => 'La Unión', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Leiva', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Linares', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Los Andes', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Magüí', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Mallama', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Mosquera', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Nariño', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Olaya Herrera', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Ospina', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Pasto', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Policarpa', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Potosí', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Providencia', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Puerres', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Pupiales', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Ricaurte', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Roberto Payán', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Samaniego', 'departamento_id' => 21],
            ['nombre_ciudad' => 'San Bernardo', 'departamento_id' => 21],
            ['nombre_ciudad' => 'San José de Albán', 'departamento_id' => 21],
            ['nombre_ciudad' => 'San Lorenzo', 'departamento_id' => 21],
            ['nombre_ciudad' => 'San Pablo', 'departamento_id' => 21],
            ['nombre_ciudad' => 'San Pedro de Cartago', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Sandoná', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Santa Bárbara', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Santacruz', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Sapuyes', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Taminango', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Tangua', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Tumaco', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Túquerres', 'departamento_id' => 21],
            ['nombre_ciudad' => 'Yacuanquer', 'departamento_id' => 21],

            // Norte de Santander
            ['nombre_ciudad' => 'Abrego', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Arboledas', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Bochalema', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Bucarasica', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Cachira', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Cacota', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Chinacota', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Chitaga', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Convencion', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Cucuta', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Cucutilla', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Durania', 'departamento_id' => 22],
            ['nombre_ciudad' => 'El Carmen', 'departamento_id' => 22],
            ['nombre_ciudad' => 'El Tarra', 'departamento_id' => 22],
            ['nombre_ciudad' => 'El Zulia', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Gramalote', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Hacari', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Herran', 'departamento_id' => 22],
            ['nombre_ciudad' => 'La Esperanza', 'departamento_id' => 22],
            ['nombre_ciudad' => 'La Playa', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Labateca', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Los Patios', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Lourdes', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Mutiscua', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Ocaña', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Pamplona', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Pamplonita', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Puerto Santander', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Ragonvalia', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Salazar', 'departamento_id' => 22],
            ['nombre_ciudad' => 'San Calixto', 'departamento_id' => 22],
            ['nombre_ciudad' => 'San Cayetano', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Santiago', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Sardinata', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Silos', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Teorama', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Tibu', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Toledo', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Villa Caro', 'departamento_id' => 22],
            ['nombre_ciudad' => 'Villa del Rosario', 'departamento_id' => 22],

            // Putumayo
            ['nombre_ciudad' => 'Colón', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Mocoa', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Orito', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Puerto Asís', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Puerto Caicedo', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Puerto Guzmán', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Puerto Leguízamo', 'departamento_id' => 23],
            ['nombre_ciudad' => 'San Francisco', 'departamento_id' => 23],
            ['nombre_ciudad' => 'San Miguel', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Santiago', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Sibundoy', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Valle del Guamuez', 'departamento_id' => 23],
            ['nombre_ciudad' => 'Villagarzón', 'departamento_id' => 23],

            // Quindio
            ['nombre_ciudad' => 'Armenia', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Buenavista', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Calarcá', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Circasia', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Córdoba', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Filandia', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Génova', 'departamento_id' => 24],
            ['nombre_ciudad' => 'La Tebaida', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Montenegro', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Pijao', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Quimbaya', 'departamento_id' => 24],
            ['nombre_ciudad' => 'Salento', 'departamento_id' => 24],

            // Risaralda
            ['nombre_ciudad' => 'Apía', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Balboa', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Belén de Umbría', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Dosquebradas', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Guática', 'departamento_id' => 25],
            ['nombre_ciudad' => 'La Celia', 'departamento_id' => 25],
            ['nombre_ciudad' => 'La Virginia', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Marsella', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Mistrató', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Pereira', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Pueblo Rico', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Quinchía', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Santa Rosa de Cabal', 'departamento_id' => 25],
            ['nombre_ciudad' => 'Santuario', 'departamento_id' => 25],

            // San Andres y Providencia
            ['nombre_ciudad' => 'Providencia', 'departamento_id' => 26],
            ['nombre_ciudad' => 'San Andrés', 'departamento_id' => 26],

            // Santander
            ['nombre_ciudad' => 'Aguada', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Albania', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Aratoca', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Barbosa', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Barichara', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Barrancabermeja', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Betulia', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Bolivar', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Bucaramanga', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Cabrera', 'departamento_id' => 27],
            ['nombre_ciudad' => 'California', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Capitanejo', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Carcasi', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Cepita', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Cerrito', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Charala', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Charta', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Chima', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Chipata', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Cimitarra', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Concepcion', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Confines', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Contratacion', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Coromoro', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Curiti', 'departamento_id' => 27],
            ['nombre_ciudad' => 'El Carmen de Chucuri', 'departamento_id' => 27],
            ['nombre_ciudad' => 'El Guacamayo', 'departamento_id' => 27],
            ['nombre_ciudad' => 'El Peñon', 'departamento_id' => 27],
            ['nombre_ciudad' => 'El Playon', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Encino', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Enciso', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Florian', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Floridablanca', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Galán', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Gambita', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Giron', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Guaca', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Guadalupe', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Guapota', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Guavata', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Guepsa', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Hato', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Jesus Maria', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Jordan', 'departamento_id' => 27],
            ['nombre_ciudad' => 'La Belleza', 'departamento_id' => 27],
            ['nombre_ciudad' => 'La Paz', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Landazuri', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Lebrija', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Los Santos', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Macaravita', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Malaga', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Matanza', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Mogotes', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Molagavita', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Ocamonte', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Oiba', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Onzaga', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Palmar', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Palmas del Socorro', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Paramo', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Piedecuesta', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Pinchote', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Puente Nacional', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Puerto Parra', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Puerto Wilches', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Rionegro', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Sabana de Torres', 'departamento_id' => 27],
            ['nombre_ciudad' => 'San Andres', 'departamento_id' => 27],
            ['nombre_ciudad' => 'San Benito', 'departamento_id' => 27],
            ['nombre_ciudad' => 'San Gil', 'departamento_id' => 27],
            ['nombre_ciudad' => 'San Joaquin', 'departamento_id' => 27],
            ['nombre_ciudad' => 'San Jose de Miranda', 'departamento_id' => 27],
            ['nombre_ciudad' => 'San Miguel', 'departamento_id' => 27],
            ['nombre_ciudad' => 'San Vicente de Chucuri', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Santa Barbara', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Santa Helena del Opon', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Simacota', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Socorro', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Suaita', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Sucre', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Surata', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Tona', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Valle de San Jose', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Velez', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Vetas', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Villanueva', 'departamento_id' => 27],
            ['nombre_ciudad' => 'Zapatoca', 'departamento_id' => 27],

            // Sucre
            ['nombre_ciudad' => 'Buenavista', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Caimito', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Chalán', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Colosó', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Corozal', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Coveñas', 'departamento_id' => 28],
            ['nombre_ciudad' => 'El Roble', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Galeras', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Guaranda', 'departamento_id' => 28],
            ['nombre_ciudad' => 'La Unión', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Los Palmitos', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Majagual', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Morroa', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Ovejas', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Palmito', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Sampués', 'departamento_id' => 28],
            ['nombre_ciudad' => 'San Benito Abad', 'departamento_id' => 28],
            ['nombre_ciudad' => 'San Juan de Betulia', 'departamento_id' => 28],
            ['nombre_ciudad' => 'San Marcos', 'departamento_id' => 28],
            ['nombre_ciudad' => 'San Onofre', 'departamento_id' => 28],
            ['nombre_ciudad' => 'San Pedro', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Santiago de Tolú', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Sincelejo', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Sucre', 'departamento_id' => 28],
            ['nombre_ciudad' => 'Tolú Viejo', 'departamento_id' => 28],

            // Tolima
            ['nombre_ciudad' => 'Alpujarra', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Alvarado', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Ambalema', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Anzoátegui', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Armero', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Ataco', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Cajamarca', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Carmen de Apicalá', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Casabianca', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Chaparral', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Coello', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Coyaima', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Cunday', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Dolores', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Espinal', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Falan', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Flandes', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Fresno', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Guamo', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Herveo', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Honda', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Ibagué', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Icononzo', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Lérida', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Líbano', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Mariquita', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Melgar', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Murillo', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Natagaima', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Ortega', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Palocabildo', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Piedras', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Planadas', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Prado', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Purificación', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Rioblanco', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Roncesvalles', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Rovira', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Saldaña', 'departamento_id' => 29],
            ['nombre_ciudad' => 'San Antonio', 'departamento_id' => 29],
            ['nombre_ciudad' => 'San Luis', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Santa Isabel', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Suárez', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Valle de San Juan', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Venadillo', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Villahermosa', 'departamento_id' => 29],
            ['nombre_ciudad' => 'Villarrica', 'departamento_id' => 29],

            // Valle del Cauca
            ['nombre_ciudad' => 'Alcalá', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Andalucía', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Ansermanuevo', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Argelia', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Bolívar', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Buenaventura', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Buga', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Bugalagrande', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Caicedonia', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Cali', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Calima', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Candelaria', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Cartago', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Dagua', 'departamento_id' => 30],
            ['nombre_ciudad' => 'El Águila', 'departamento_id' => 30],
            ['nombre_ciudad' => 'El Cairo', 'departamento_id' => 30],
            ['nombre_ciudad' => 'El Cerrito', 'departamento_id' => 30],
            ['nombre_ciudad' => 'El Dovio', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Florida', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Ginebra', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Guacarí', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Jamundí', 'departamento_id' => 30],
            ['nombre_ciudad' => 'La Cumbre', 'departamento_id' => 30],
            ['nombre_ciudad' => 'La Unión', 'departamento_id' => 30],
            ['nombre_ciudad' => 'La Victoria', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Obando', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Palmira', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Pradera', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Restrepo', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Riofrío', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Roldanillo', 'departamento_id' => 30],
            ['nombre_ciudad' => 'San Pedro', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Sevilla', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Toro', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Trujillo', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Tuluá', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Ulloa', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Versalles', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Vijes', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Yotoco', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Yumbo', 'departamento_id' => 30],
            ['nombre_ciudad' => 'Zarzal', 'departamento_id' => 30],

            // Vaupes
            ['nombre_ciudad' => 'Carurú', 'departamento_id' => 31],
            ['nombre_ciudad' => 'Mitú', 'departamento_id' => 31],
            ['nombre_ciudad' => 'Taraira', 'departamento_id' => 31],
            ['nombre_ciudad' => 'Pacoa', 'departamento_id' => 31],
            ['nombre_ciudad' => 'Papunaua', 'departamento_id' => 31],
            ['nombre_ciudad' => 'Yavaraté', 'departamento_id' => 31],

            // Vichada
            ['nombre_ciudad' => 'Cumaribo', 'departamento_id' => 32],
            ['nombre_ciudad' => 'La Primavera', 'departamento_id' => 32],
            ['nombre_ciudad' => 'Puerto Carreño', 'departamento_id' => 32],
            ['nombre_ciudad' => 'Santa Rosalía', 'departamento_id' => 32],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ciudads');
    }
};
